

services:
  # --------------------------
  # Tailscale sidecar
  # --------------------------
  tailscale-sc-server:
    image: tailscale/tailscale:latest
    container_name: tailscale-sc-server
    hostname: srt-server
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY_SERVER}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-state-server:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - watchtower.group=server
      - com.centurylinklabs.watchtower.enable=true

  # --------------------------
  # SRT Live Server
  # --------------------------
  srt-server:
    #image: alaamr/srt-ts-server:latest
    build:
      context: ./srt-server
      dockerfile: Dockerfile
    container_name: srt-server
    network_mode: service:tailscale-sc-server
    depends_on:
      - tailscale-sc-server
    restart: unless-stopped
    labels:
      - watchtower.group=server
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - SRT_PORT=1936
      - SERVER_LOCAL_ENCODER=${SERVER_LOCAL_ENCODER}
      - SERVER_LOCAL_ENCODER_CRF=${SERVER_LOCAL_ENCODER_CRF}
      - SERVER_LOCAL_ENCODER_PRESET=${SERVER_LOCAL_ENCODER_PRESET}
      - ARCHIVE_SEGMENT_DURATION=${ARCHIVE_SEGMENT_DURATION}
      - SERVER_RETENTION_PERIOD=${SERVER_RETENTION_PERIOD}
      - SERVER_CLEANER_INTERVAL=${SERVER_CLEANER_INTERVAL}
    volumes:
      - /mnt/srt-sever/archive:/archive
      - /mnt/srt-sever/recordings:/recordings

  nginx-server:
    #image: alaamr/nginx-server:latest
    build:
      context: ./nginx-server/
      dockerfile: Dockerfile
    container_name: nginx-server
    volumes:
      - /mnt/srt-sever/archive:/archive:ro
      - /mnt/srt-sever/recordings:/recordings:ro
    depends_on:
      - tailscale-sc-server
      - srt-server
    network_mode: service:tailscale-sc-server
    restart: unless-stopped

  # --------------------------
  # Watchtower for auto-updates
  # --------------------------
  watchtower-server:
    image: containrrr/watchtower:latest
    container_name: watchtower-server
    environment:
      - DOCKER_API_VERSION=1.52 # Watchtower complains otherwise, see https://github.com/containrrr/watchtower/issues/2126
    command:
      - "--label-enable"
      - "--scope"
      - "server"
      - "--cleanup"
      - "--interval"
      - "60"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  tailscale-state-server:
